name       : libxkbcommon
version    : 0.8.2
release    : 8
source     :
    - https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-0.8.2.tar.gz : fd19874aefbcbc9da751292ba7abee8952405cd7d9042466e41a9c6ed3046322
license    : MIT
component  : desktop.library
summary    : xkbcommon is a library to handle keyboard description
description: |
    xkbcommon is a library to handle keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; currently that includes Wayland, kmscon, GTK+, Qt, Clutter, and more. Despite the name, it isn't actually used by anything X11 (yet).
emul32     : yes
builddeps  :
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-macros)
    - pkgconfig32(xcb-xkb)
rundeps    :
    - xkeyboard-config
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
