name       : libxkbcommon
version    : 1.5.0
release    : 13
source     :
    - https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-1.5.0.tar.gz : 053e6a6a2c3179eba20c3ada827fb8833a6663b7ffd278fdb8530c3cbf924780
license    : MIT
component  : desktop.library
summary    : xkbcommon is a library to handle keyboard description
description: |
    xkbcommon is a library to handle keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; currently that includes Wayland, kmscon, GTK+, Qt, Clutter, and more. Despite the name, it isn't actually used by anything X11 (yet).
emul32     : yes
builddeps  :
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcb-xkb)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-macros)
rundeps    :
    - xkeyboard-config
setup      : |
    %meson_configure -Denable-docs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
