name       : libxkbcommon
version    : 0.8.2
release    : 7
source     :
    - https://xkbcommon.org/download/libxkbcommon-0.8.2.tar.xz : 7ab8c4b3403d89d01898066b72cb6069bddeb5af94905a65368f671a026ed58c
license    : MIT
component  : desktop.library
summary    : xkbcommon is a library to handle keyboard description
description: |
    xkbcommon is a library to handle keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; currently that includes Wayland, kmscon, GTK+, Qt, Clutter, and more. Despite the name, it isn't actually used by anything X11 (yet).
emul32     : yes
builddeps  :
    - pkgconfig(xkeyboard-config)
    - pkgconfig32(xcb-xkb)
rundeps    :
    - xkeyboard-config
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
