name        : libxkbcommon
version     : 0.5.0
release     : 4
source      :
    - http://xkbcommon.org/download/libxkbcommon-0.5.0.tar.xz : 90bd7824742b9a6f52a6cf80e2cadd6f5349cf600a358d08260772615b89d19c
license     : MIT
component   : desktop.library
summary     : xkbcommon is a library to handle keyboard description
description : |
    xkbcommon is a library to handle keyboard descriptions, including loading them from disk, parsing them and handling their state. It's mainly meant for client toolkits, window systems, and other system applications; currently that includes Wayland, kmscon, GTK+, Qt, Clutter, and more. Despite the name, it isn't actually used by anything X11 (yet).
emul32      : yes
builddeps   :
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xcb-xkb)
    - pkgconfig32(xcb-xkb)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
